import type { Metadata } from "next";
import { Urbanist as UrbanistFont } from "next/font/google"; // Rename the import to avoid conflicts
import "./globals.css";
import Header from "@/components/Header";

const urbanist = UrbanistFont({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-900 text-slate-100 ">
      
      <body className={urbanist.className}>
      <Header/>
        {children}
      </body>
    </html>
  );
}
